In [1]:
import numpy as np


In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [13]:
def deriv(x):
    return x*(1-x)

In [14]:
x=np.array([[0,0,1],
          [0,1,1,],
          [1,0,1],
          [1,1,1]])

In [15]:
y=-np.array([[0],
            [1],
            [1],
            [0]])

In [16]:
alphas=[0.001,0.01,0.1,1,10,100]

In [18]:
for alpha in alphas:
    print("\n Training with alpha="+str(alpha))
    np.random.seed(1)
    print(np.random.random((1,1)))
    synapse_0=np.random.random((3,4))-1
    synapse_1=np.random.random((4,1))-1
    print(synapse_0)
    print(synapse_1)

    for j in range(60000):
        layer_0=x
        layer_1=sigmoid(np.dot(layer_0,synapse_0))
        layer_2=sigmoid(np.dot(layer_1,synapse_1))

        layer_2_error=layer_2-y

        if j%1000==0:
            print("error after"+str(j)+"iteration="+str(np.mean(np.abs(layer_2))))

        layer_2_delta=layer_2_error*deriv(layer_2)
        layer_1_error=layer_2_delta.dot(synapse_1.T)
        layer_1_delta=layer_1_error*deriv(layer_1)
        synapse_1-=alpha*(layer_1.T.dot(layer_2_delta))
        synapse_0-=alpha*(layer_0.T.dot(layer_1_delta))



 Training with alpha=0.001
[[0.417022]]
[[-0.27967551 -0.99988563 -0.69766743 -0.85324411]
 [-0.90766141 -0.81373979 -0.65443927 -0.60323253]
 [-0.46118327 -0.58080549 -0.3147805  -0.79554775]]
[[-0.12188256]
 [-0.97261241]
 [-0.32953249]
 [-0.5826952 ]]
error after0iteration=0.39404257140039395
error after1000iteration=0.3398304831357498
error after2000iteration=0.28253436387835096
error after3000iteration=0.22545745428951997
error after4000iteration=0.17432544006975959
error after5000iteration=0.13332958733240646
error after6000iteration=0.10288830660875536
error after7000iteration=0.08100905456511401
error after8000iteration=0.06529449113484473
error after9000iteration=0.0538282687326576
error after10000iteration=0.04527588699690604
error after11000iteration=0.038748504315678556
error after12000iteration=0.033657089780371734
error after13000iteration=0.029606609200914166
error after14000iteration=0.026327120350184294
error after15000iteration=0.02363027546119857
error after16000ite

error after41000iteration=3.377319838022356e-05
error after42000iteration=3.296210045585063e-05
error after43000iteration=3.218921631343617e-05
error after44000iteration=3.145190769618098e-05
error after45000iteration=3.0747773604940296e-05
error after46000iteration=3.0074624229613292e-05
error after47000iteration=2.9430458241970114e-05
error after48000iteration=2.8813442955102207e-05
error after49000iteration=2.8221896936175383e-05
error after50000iteration=2.7654274725868204e-05
error after51000iteration=2.710915337272884e-05
error after52000iteration=2.658522053593919e-05
error after53000iteration=2.608126394751195e-05
error after54000iteration=2.5596162056148598e-05
error after55000iteration=2.512887570106656e-05
error after56000iteration=2.4678440685949666e-05
error after57000iteration=2.4243961141544003e-05
error after58000iteration=2.3824603580919475e-05
error after59000iteration=2.341959156453826e-05

 Training with alpha=1
[[0.417022]]
[[-0.27967551 -0.99988563 -0.69766743 -0.

error after18000iteration=3.155996966869452e-33
error after19000iteration=3.155996966869452e-33
error after20000iteration=3.155996966869452e-33
error after21000iteration=3.155996966869452e-33
error after22000iteration=3.155996966869452e-33
error after23000iteration=3.155996966869452e-33
error after24000iteration=3.155996966869452e-33
error after25000iteration=3.155996966869452e-33
error after26000iteration=3.155996966869452e-33
error after27000iteration=3.155996966869452e-33
error after28000iteration=3.155996966869452e-33
error after29000iteration=3.155996966869452e-33
error after30000iteration=3.155996966869452e-33
error after31000iteration=3.155996966869452e-33
error after32000iteration=3.155996966869452e-33
error after33000iteration=3.155996966869452e-33
error after34000iteration=3.155996966869452e-33
error after35000iteration=3.155996966869452e-33
error after36000iteration=3.155996966869452e-33
error after37000iteration=3.155996966869452e-33
error after38000iteration=3.155996966869

In [ ]:
for j in range(6000)